export type CurrencyEntry = {
  country: string;
  code: string;
  symbol: string;
};

// This list focuses on common/official currencies and their common text symbols.
// Some currencies share symbols; some don't have a single-character symbol and use the code.
export const currencies: CurrencyEntry[] = [
  { country: "United States", code: "USD", symbol: "$" },
  { country: "European Union", code: "EUR", symbol: "€" },
  { country: "United Kingdom", code: "GBP", symbol: "£" },
  { country: "Japan", code: "JPY", symbol: "¥" },
  { country: "Canada", code: "CAD", symbol: "$" },
  { country: "Australia", code: "AUD", symbol: "$" },
  { country: "Switzerland", code: "CHF", symbol: "CHF" },
  { country: "China", code: "CNY", symbol: "¥" },
  { country: "India", code: "INR", symbol: "₹" },
  { country: "Nigeria", code: "NGN", symbol: "₦" },
  { country: "Mexico", code: "MXN", symbol: "$" },
  { country: "Brazil", code: "BRL", symbol: "R$" },
  { country: "South Africa", code: "ZAR", symbol: "R" },
  { country: "South Korea", code: "KRW", symbol: "₩" },
  { country: "Turkey", code: "TRY", symbol: "₺" },
  { country: "Russia", code: "RUB", symbol: "₽" },
  { country: "Indonesia", code: "IDR", symbol: "Rp" },
  { country: "Saudi Arabia", code: "SAR", symbol: "﷼" },
  { country: "United Arab Emirates", code: "AED", symbol: "د.إ" },
  { country: "Argentina", code: "ARS", symbol: "$" },
  { country: "Sweden", code: "SEK", symbol: "kr" },
  { country: "Norway", code: "NOK", symbol: "kr" },
  { country: "Denmark", code: "DKK", symbol: "kr" },
  { country: "Poland", code: "PLN", symbol: "zł" },
  { country: "Israel", code: "ILS", symbol: "₪" },
  { country: "Egypt", code: "EGP", symbol: "£" },
  { country: "Philippines", code: "PHP", symbol: "₱" },
  { country: "Thailand", code: "THB", symbol: "฿" },
  { country: "Malaysia", code: "MYR", symbol: "RM" },
  { country: "Singapore", code: "SGD", symbol: "$" },
  { country: "New Zealand", code: "NZD", symbol: "$" },
  { country: "Vietnam", code: "VND", symbol: "₫" },
  { country: "Chile", code: "CLP", symbol: "$" },
  { country: "Colombia", code: "COP", symbol: "$" },
  { country: "Peru", code: "PEN", symbol: "S/" },
  { country: "Czech Republic", code: "CZK", symbol: "Kč" },
  { country: "Hungary", code: "HUF", symbol: "Ft" },
  { country: "Iceland", code: "ISK", symbol: "kr" },
  { country: "Ukraine", code: "UAH", symbol: "₴" },
  { country: "Romania", code: "RON", symbol: "lei" },
  { country: "Bangladesh", code: "BDT", symbol: "৳" },
  { country: "Pakistan", code: "PKR", symbol: "₨" },
  { country: "Sri Lanka", code: "LKR", symbol: "₨" },
  { country: "Morocco", code: "MAD", symbol: "د.م." },
  { country: "Kenya", code: "KES", symbol: "KSh" },
  { country: "Ghana", code: "GHS", symbol: "₵" },
  { country: "Ethiopia", code: "ETB", symbol: "Br" },
  { country: "Tunisia", code: "TND", symbol: "د.ت" },
  { country: "Algeria", code: "DZD", symbol: "دج" },
  { country: "Kazakhstan", code: "KZT", symbol: "₸" },
  { country: "Belarus", code: "BYN", symbol: "Br" },
  { country: "Bolivia", code: "BOB", symbol: "Bs." },
  { country: "Venezuela", code: "VEF", symbol: "Bs." },
  { country: "Croatia", code: "HRK", symbol: "kn" },
  { country: "Bulgaria", code: "BGN", symbol: "лв" },
  { country: "Slovenia", code: "EUR", symbol: "€" },
  { country: "Slovakia", code: "EUR", symbol: "€" },
  { country: "Latvia", code: "EUR", symbol: "€" },
  { country: "Lithuania", code: "EUR", symbol: "€" },
  { country: "Estonia", code: "EUR", symbol: "€" },
  { country: "Cyprus", code: "EUR", symbol: "€" },
  { country: "Malta", code: "EUR", symbol: "€" },
  // Fallback: many currencies without a simple symbol use the ISO code
  { country: "Afghanistan", code: "AFN", symbol: "AFN" },
  { country: "Armenia", code: "AMD", symbol: "֏" },
  { country: "Azerbaijan", code: "AZN", symbol: "₼" },
  { country: "Bahrain", code: "BHD", symbol: "BD" },
  { country: "Barbados", code: "BBD", symbol: "$" },
  { country: "Belize", code: "BZD", symbol: "$" },
  { country: "Bhutan", code: "BTN", symbol: "Nu." },
  { country: "Brunei", code: "BND", symbol: "$" },
  { country: "Cambodia", code: "KHR", symbol: "៛" },
  { country: "Cameroon", code: "XAF", symbol: "FCFA" },
  { country: "Central African Republic", code: "XAF", symbol: "FCFA" },
  { country: "Chad", code: "XAF", symbol: "FCFA" },
  { country: "Comoros", code: "KMF", symbol: "CF" },
  { country: "Côte d’Ivoire", code: "XOF", symbol: "CFA" },
  { country: "Djibouti", code: "DJF", symbol: "Fdj" },
  { country: "Dominican Republic", code: "DOP", symbol: "RD$" },
  { country: "Fiji", code: "FJD", symbol: "$" },
  { country: "Guatemala", code: "GTQ", symbol: "Q" },
  { country: "Honduras", code: "HNL", symbol: "L" },
  { country: "Iraq", code: "IQD", symbol: "ع.د" },
  { country: "Jordan", code: "JOD", symbol: "د.ا" },
  { country: "Kuwait", code: "KWD", symbol: "د.ك" },
  { country: "Laos", code: "LAK", symbol: "₭" },
  { country: "Lebanon", code: "LBP", symbol: "ل.ل" },
  { country: "Libya", code: "LYD", symbol: "ل.د" },
  { country: "Macedonia", code: "MKD", symbol: "ден" },
  { country: "Moldova", code: "MDL", symbol: "L" },
  { country: "Monaco", code: "EUR", symbol: "€" },
  { country: "Montenegro", code: "EUR", symbol: "€" },
  { country: "Namibia", code: "NAD", symbol: "$" },
  { country: "Oman", code: "OMR", symbol: "ر.ع." },
  { country: "Panama", code: "PAB", symbol: "B/." },
  { country: "Paraguay", code: "PYG", symbol: "Gs" },
  { country: "Qatar", code: "QAR", symbol: "ر.ق" },
  { country: "Seychelles", code: "SCR", symbol: "₨" },
  { country: "Singapore", code: "SGD", symbol: "$" },
  { country: "Suriname", code: "SRD", symbol: "$" },
  { country: "Tanzania", code: "TZS", symbol: "TSh" },
  { country: "Uganda", code: "UGX", symbol: "USh" },
  { country: "Uzbekistan", code: "UZS", symbol: "soʻm" },
  { country: "Zambia", code: "ZMW", symbol: "ZK" },
  { country: "Zimbabwe", code: "ZWL", symbol: "Z$" },
];

export default currencies;
